export { default as Home } from './Home'
export { default as NewRecipe } from './Recipe/New'
export { default as UpdateRecipe } from './Recipe/Update'
export { default as Login } from './User/Login'
export { default as Register } from './User/Register'
export { default as Crawl } from './Crawler/Crawl'