FROM node:16-alpine

WORKDIR /usr/src/app
COPY package*.json ./

RUN apk add --no-cache curl
RUN npm install -g nodemon
RUN npm install -g knex
RUN npm install

COPY . .

EXPOSE 4000

CMD ["./docker/wait-for-elastic.sh", "http://elastic:9200", "npm run start:dev"]
