version: '3.7'

services:
  api:
    container_name: api
    restart: on-failure
    tty: true
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - ./api:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    expose:
      - ${API_PORT}
    depends_on:
      - database
      - elastic
    networks:
      - app

  client:
    container_name: client
    restart: on-failure
    stdin_open: true
    build:
      context: ./client
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - ./client:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    networks:
      - app

  database:
    container_name: database
    build:
      context: ./docker
      dockerfile: Dockerfile.postgres.dev
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    depends_on:
      - elastic
    networks:
      - app

  adminer:
    image: adminer
    container_name: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - app

  elastic:
    image: elasticsearch:7.8.0
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic02
      - cluster.initial_master_nodes=elastic,elastic02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_PORT}:${ELASTIC_PORT}
    networks:
      - app
    
  elastic02:
    image: elasticsearch:7.8.0
    container_name: elastic02
    environment:
      - node.name=elastic02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic
      - cluster.initial_master_nodes=elastic,elastic02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data02:/usr/share/elasticsearch/data
    networks:
      - app

  kibana:
    image: kibana:7.8.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:${ELASTIC_PORT}
      ELASTICSEARCH_HOSTS: http://elastic:${ELASTIC_PORT}
    networks:
      - app

volumes:
  database-data:
    name: postgres-data
  elastic-data:
    name: elastic-data
    driver: local
  elastic-data02:
    name: elastic-data02
    driver: local

networks:
  app:
    name: app
    driver: bridge
