version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./dev.env
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    networks: 
      - api
    depends_on:
      - database

  database:
    image: "postgres"
    env_file:
      - ./dev.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - api

volumes:
  database-data:

networks:
  api:
    name: api