FROM node:current-alpine

WORKDIR /usr/src/app
COPY package*.json ./

RUN apk add --no-cache curl
RUN npm install -g nodemon
RUN npm install -g knex
RUN npm install

COPY . .

EXPOSE 4000

# TODO Run Migrations and Seeds when building the image the first time
# Need to wait for Elasticsearch cluster to be ready to connect to.
# https://github.com/elastic/elasticsearch-py/issues/778#issuecomment-384389668
# CMD ["sh", "./docker/wait-for-elastic.sh", "http://elastic:9200", "npm run migrate:latest"]

CMD ["npm", "run", "start:dev"]
